config/routes.rb
Phoneclone::Application.routes.draw do


  get "adminactions/deletelisting"
  get "adminactions/deletecomment"
  get "adminactions/modifylisting"
  get "adminactions/approvecomment"
  get "adminactions/approvelisting"
  get "adminactions/dashboard"
  get "adminactions/noimagesphones"
  
  get "transactions/initiatetransaction"
  post "transactions/processtransaction"
  get "transactions/completetransaction"
  get "transactions/failedtransaction"
  post 'transactions/notify_action'  => 'transactions#notify_action'
  
  get "phones/index"
  get "phones/new"
  get "phones/create"
  get "pages/phones"
  get "pages/contact"
  get "pages/faq"
  get "pages/sellerfaq"
  get "pages/buyerfaq"
  get "pages/devicesfaq"
  get "pages/paymentsfaq"
  get "pages/terms"
  get "pages/listing"
  get "pages/buy"
  get "pages/sell"
  get "pages/searchresults"
  get 'pages/iphones-for-sale' => 'pages#alliphones'
  get 'pages/ipads-for-sale' => 'pages#allipads'
  get "pages/thanksandshare"
  
  
  
  get "index/new"
  get "index/create"
  root :to => 'pages#home'
  get 'pages/about' => 'pages#about'
  get  'pages/help' => 'pages#help'
  get  'pages/dashboard' => 'pages#dashboard', :as => :dashboard
  
  resources :trackcodes
  resources :comments
   resources :reviews
   resources :phones
  resources :accounts
  resources :listings
  resources :profiles do
     member do
        get :vote_for_profile
        get :vote_against_profile
        
     end
  end
  
 
  
  devise_for :admins
  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" } 



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= (yield(:title) + " - " unless yield(:title).blank?).to_s + "Phonesalad" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.js"></script>
<meta name="viewport" content="initial-scale=1">

  <%= csrf_meta_tags %>
</head>
<body>
			<nav class="navbar navbar-default offshadow" role="navigation">
			  <div class="container-fluid">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			
			      </button>
			    <h4 class="small-logo pull-left"><a href="<%=root_url%>">phonesalad</a></h4>
				
			    </div>

			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			  
			      <ul class="nav navbar-nav navbar-right">
			        <li><a href="<%= root_url %>">Home</a></li>
					
					<li><a href="/pages/iphones-for-sale">iPhones</a></li>
						<li><a href="/pages/ipads-for-sale">iPads</a></li>
				
					<li class="divider"></li>
					
					<li>
							<% if user_signed_in? %>
						<%= link_to "My Dashboard", dashboard_url %></li>
						
						<li><%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %>
						<% else %>
					     	<li> <%= link_to "Sign in", new_user_session_path %></li>
					     	<li> <%= link_to "Sign up", new_user_registration_path %>

						<% end %>
					</li>
			          </ul>
			        </li>
			      </ul>
			
		
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>

				

	<% if flash[:notice] %>
	<div class='alert top-alert <% if flash[:notice] =~ /Success/i %> alert-success <% else %> alert-danger<% end %>' data-dismiss="alert">
	<p><%= flash[:notice] %></p>
	</div>
	<% end %>
<%= yield %>


<div id="footer" class="offshadow">
	<div id="credits" class="centered-text softshadow"><p>All rights reserved.</p></div>
</div>
</body>
</html>

app/views/layouts/forms.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buy and sell iPhones & iPads in Singapore | Phonesalad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.js"></script>
<meta name="viewport" content="initial-scale=1">

  <%= csrf_meta_tags %>
</head>
<body id="forms">
	<% if user_signed_in? %>
		<nav class="navbar navbar-default offshadow" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		    <h4 class="small-logo pull-left"><a href="<%=root_url%>">phonesalad</a></h4>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		   
		     
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="<%= root_url %>">Home</a></li>
				
				<li><a href="/pages/iphones-for-sale">iPhones</a></li>
					<li><a href="/pages/ipads-for-sale">iPads</a></li>
				
				<li class="divider"></li>
				
				<li>
					<%= link_to "My Dashboard", dashboard_url %></li>
					
					<li><%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %>
				
				</li>
		          </ul>
		        </li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
	<%end%>
	
<%= yield %>

<div id="footer">
	<div id="credits" class="centered-text softshadow"><p>All rights reserved.</p></div>
</div>


</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buy and sell iPhones & iPads in Singapore | Phonesalad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.js"></script>
<meta name="viewport" content="initial-scale=1">

  <%= csrf_meta_tags %>
</head>
<body>
		<nav class="navbar navbar-default offshadow" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		    <h4 class="small-logo pull-left"><a href="<%=root_url%>">phonesalad</a></h4>
			
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		   
		     	<% if user_signed_in? %>
			
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="<%= root_url %>">Home</a></li>
				
				<li><a href="/pages/iphones-for-sale">iPhones</a></li>
					<li><a href="/pages/ipads-for-sale">iPads</a></li>
					
				<li class="divider"></li>
				
				<li>
					<%= link_to "My Dashboard", dashboard_url %></li>
					
					<li><%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %>
				
				</li>
		          </ul>
		
		<% else %>
		<ul class="nav navbar-nav navbar-right">
	        <li><a class="btn btn-sm btn-default" href="<%= new_user_session_path %>">Sign in</a></li>	
	          </ul>
		
				<%end%>
	
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>

<%= yield %>

<div id="footer" class="offshadow">

	<div id="credits" class="centered-text softshadow"><p>All rights reserved.</p></div>
</div>
</body>
</html>